src/objects/Scope__c.object
<CustomObject>
    <label>Scope</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>Scope__c</referenceTo>
        <relationshipLabel>Scoping Features</relationshipLabel>
        <relationshipName>Scoping_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoping Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

My Dev Org/src/classes/ScopingFeatureModel.cls
public with sharing class ScopingFeatureModel {
	public Id scopeId { get; set; }
	public Id id { get; set; }
	public String name { get; set; }
	
	public List<ScopingTaskModel> tasks
	{
		get
		{
			if (null == tasks)
				tasks = new List<ScopingTaskModel>();
			return tasks;
		}
		private set;
	}
	
	public ScopingFeatureModel()//Id scopeId)
	{
		//this.scopeId = scopeId;
	}
	
	public void addTask()
	{
		tasks.add(new ScopingTaskModel());
	}
	
	public Scoping_Feature__c getRecord()
	{
		Scoping_Feature__c record = new Scoping_Feature__c();
		
		record.Scope__c = scopeId;
		record.Name = name;
		
		return record;
	}
}