src/objects/Scope__c.object
<CustomObject>
    <label>Scope</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>Scope__c</referenceTo>
        <relationshipLabel>Scoping Features</relationshipLabel>
        <relationshipName>Scoping_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoping Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Task__c.object
<CustomObject>
    <fields>
        <fullName>Scoping_Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scoping Feature</label>
        <referenceTo>Scoping_Feature__c</referenceTo>
        <relationshipLabel>Scoping Tasks</relationshipLabel>
        <relationshipName>Scoping_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoping Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

My Dev Org/src/classes/ScopingTemplateController.cls
global with sharing class ScopingTemplateController {
	public ScopeModel scope
	{
		get
		{
			if (null == scope)
				scope = new ScopeModel();
			
			return scope;
		}
		set;
	}
	
	public void addFeature()
	{
		scope.addFeature();
	}
	
	public void saveScope()
	{
		Scope__c scopeRecord = scope.getRecord();
		insert scopeRecord;
		
		List<Scoping_Feature__c> featureRecords = new List<Scoping_Feature__c>();
		List<Scoping_Task__c> taskRecords = new List<Scoping_Task__c>();
		
		for( ScopingFeatureModel feature : scope.features )
		{
			feature.scopeId = scopeRecord.Id;

			Scoping_Feature__c featureRecord = feature.getRecord();
			
			featureRecords.add( feature.getRecord() );
			
			insert featureRecord;
			
			feature.Id = featureRecord.Id;
		}
		
		for( ScopingFeatureModel feature : scope.features )
		{
			for( ScopingTaskModel task : feature.tasks )
			{
				task.featureId = feature.Id;
				
				taskRecords.add( task.getRecord() );
			}
		}
		
		insert taskRecords;
	}
	
	@RemoteAction global static ScopeModel getNewModel()
	{
		ScopeModel model = new ScopeModel();
		model.name = 'SCOPE';
		model.addFeature();
		model.features[0].name = 'FEATURE';
		model.features[0].addTask();
		model.features[0].tasks[0].name = 'TASK';
		return model;
	}
	
	@RemoteAction global static void saveModel( ScopeModel model )
	{
		upsert model;
	}
}