src/objects/Scope__c.object
<CustomObject>
    <label>Scope</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>Scope__c</referenceTo>
        <relationshipLabel>Scoping Features</relationshipLabel>
        <relationshipName>Scoping_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scoping Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Task__c.object
<CustomObject>
    <fields>
        <fullName>Scoping_Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scoping Feature</label>
        <referenceTo>Scoping_Feature__c</referenceTo>
        <relationshipLabel>Scoping Tasks</relationshipLabel>
        <relationshipName>Scoping_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scoping Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScopingFeatureModel.cls
public with sharing class ScopingFeatureModel extends ListModel.Element {
	public Id id { get; private set; }
	public Id scopeId	{ get; set; }
	public String name	{ get; set; }
	private Scoping_Feature__c record; 
	
	private ListModel taskList;
	
	public List<ScopingTaskModel> tasks
	{
		get
		{
			List<ScopingTaskModel> models = new List<ScopingTaskModel>();
			for( ListModel.Element el : taskList.getList() )
			{
				models.add((ScopingTaskModel)el);
			}
			return models;
		}
	}
	
	public ScopingFeatureModel()
	{
		taskList = new ListModel();
	}
	
	public ScopingTaskModel addTask()
	{
		ScopingTaskModel task = new ScopingTaskModel();
		taskList.add( task );
		
		if( null != id ) task.featureId = id;
		
		return task;
	}
	
	public ScopingTaskModel removeTask( Integer index )
	{
		return (ScopingTaskModel)taskList.remove( index );
	}
	
	public void putTask( Integer index, ScopingTaskModel task )
	{
		taskList.put( index, task );
	}
	
	public void moveTask( Integer fromIndex, Integer toIndex )
	{
		taskList.move( fromIndex, toIndex );
	}
	
	public ScopingTaskModel addTask( Scoping_Task__c taskRecord )
	{
		ScopingTaskModel task = new ScopingTaskModel();
		
		task.setRecord(taskRecord);
		
		taskList.add(task);
		
		return task;
	}
	
	public void setRecord( Scoping_Feature__c recordIn )
	{
		id		= recordIn.Id;
		scopeId = recordIn.Scope__c;
		name	= recordIn.Name;
	}
	
	public Scoping_Feature__c getRecord()
	{
		if( null == record )
		{
			record = new Scoping_Feature__c( Id = id );
			
			record.Scope__c = scopeId;
			record.Name		= name;
		}
		
		record.Sort_Order__c = index;
		
		return record;
	}
}