src/objects/Scope__c.object
<CustomObject>
    <fields>
        <fullName>Buffer__c</fullName>
        <label>Buffer</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Code_Review__c</fullName>
        <label>Code Review</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Management__c</fullName>
        <label>Project Management</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reactive__c</fullName>
        <label>Reactive</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sum_of_X50_Estimates__c</fullName>
        <label>Sum of 50% Estimates</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Testing__c</fullName>
        <label>Testing</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Buffer__c +  Code_Review__c +  Deployment__c  +  Reactive__c  +  Project_Management__c +  Testing__c +  Sum_of_X50_Estimates__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>Scope__c</referenceTo>
        <relationshipLabel>Scoping Features</relationshipLabel>
        <relationshipName>Scoping_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scoping Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Task__c.object
<CustomObject>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Scoping_Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scoping Feature</label>
        <referenceTo>Scoping_Feature__c</referenceTo>
        <relationshipLabel>Scoping Tasks</relationshipLabel>
        <relationshipName>Scoping_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X50_Estimate__c</fullName>
        <label>50% Estimate</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X90_Estimate__c</fullName>
        <label>90% Estimate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Scoping Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScopingTemplateController.cls
global with sharing class ScopingTemplateController {
	public static String OLD_FEATURE_TAG	{ get { return 'X_ofi'; } }
	public static String OLD_TASK_TAG		{ get { return 'X_oti'; } }
	public static String NEW_FEATURE_TAG	{ get { return 'X_nfi'; } }
	public static String NEW_TASK_TAG		{ get { return 'X_nti'; } }
	
	public ScopeModel scope
	{
		get
		{
			if (null == scope){
				
				Id scopeId = ApexPages.currentPage().getParameters().get('id');
				if (null != scopeId)
				{
					scope = loadScope(scopeId);
				}
				else
				{
					scope = new ScopeModel();
					ScopingFeatureModel feature = scope.addFeature();
					feature.addTask();
				}
					
			}	
			return scope;
		}
		set;
	}
	
	public void addFeature()
	{
		scope.addFeature();
	}
	
	public void addTask()
	{
		Integer featureIndex = Integer.valueOf( ApexPages.currentPage().getParameters().get( NEW_FEATURE_TAG ) );
		scope.features[featureIndex].addTask();
	}
	
	public void moveTask()
	{
		try{
			Map<String, String> params = ApexPages.currentPage().getParameters();
		
			Integer oldFeatureIndex	= Integer.valueOf( params.get( OLD_FEATURE_TAG ) ),
					oldTaskIndex	= Integer.valueOf( params.get( OLD_TASK_TAG ) ),
					newFeatureIndex	= Integer.valueOf( params.get( NEW_FEATURE_TAG ) ),
					newTaskIndex	= Integer.valueOf( params.get( NEW_TASK_TAG ) );
			
			if( oldFeatureIndex == newFeatureIndex )
			{
				scope.features[oldFeatureIndex].moveTask( oldTaskIndex, newTaskIndex );
			}
			else
			{
				ScopingTaskModel task = scope.features[oldFeatureIndex].removeTask( oldTaskIndex );
				scope.features[newFeatureIndex].putTask( newTaskIndex, task );
			}
		}
		catch( Exception e )
		{
			ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.FATAL, e.getMessage() ) );
		}
	}
	
	public void moveFeature()
	{
		try{
			Map<String, String> params = ApexPages.currentPage().getParameters();
		
			Integer oldFeatureIndex	= Integer.valueOf( params.get( OLD_FEATURE_TAG ) ),
					newFeatureIndex	= Integer.valueOf( params.get( NEW_FEATURE_TAG ) );
			
			scope.moveFeature( oldFeatureIndex, newFeatureIndex );
		}
		catch( Exception e )
		{
			ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.FATAL, e.getMessage() ) );
		}
	}
	
	public ScopeModel loadScope( Id scopeId )
	{
		ScopeModel scope = new ScopeModel();
		
		Scope__c scopeRecord = [SELECT Id, Name,
									   Code_Review__c, Deployment__c, Project_Management__c, Buffer__c,
									   Reactive__c, Testing__c, Sum_of_X50_Estimates__c, Total__c
								FROM Scope__c
								WHERE Id = :scopeId];
								
		scope.setRecord( scopeRecord );
		
		List<Scoping_Feature__c> featureRecords = [SELECT Id, Name, Scope__c,
														(SELECT Id, Name, Scoping_Feature__c,
																Details__c, X50_Estimate__c, X90_Estimate__c
														 FROM Scoping_Tasks__r
														 ORDER BY Sort_Order__c)
													FROM Scoping_Feature__c
													WHERE Scope__c = :scopeId
													ORDER BY Sort_Order__c];
		
		for( Scoping_Feature__c featureRecord : featureRecords )
		{
			ScopingFeatureModel feature = scope.addFeature(featureRecord);
			
			for( Scoping_Task__c taskRecord : featureRecord.Scoping_Tasks__r )
			{
				feature.addTask(taskRecord);
			}
		}
		
		return scope;
	}
	
	public void saveScope()
	{
		Scope__c scopeRecord = scope.getRecord();
		upsert scopeRecord;
		
		List<Scoping_Feature__c> featureRecords = new List<Scoping_Feature__c>();
		List<Scoping_Task__c> taskRecords = new List<Scoping_Task__c>();
		
		for( ScopingFeatureModel feature : scope.features )
		{
			feature.scopeId = scopeRecord.Id;

			Scoping_Feature__c featureRecord = feature.getRecord();
			
			featureRecords.add( feature.getRecord() );
			
			upsert featureRecord;
			
			for( ScopingTaskModel task : feature.tasks )
			{
				task.featureId = featureRecord.Id;
				
				taskRecords.add( task.getRecord() );
			}
		}
		
		upsert taskRecords;
	}
}