src/objects/Scope__c.object
<CustomObject>
    <label>Scope</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>Scope__c</referenceTo>
        <relationshipLabel>Scoping Features</relationshipLabel>
        <relationshipName>Scoping_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoping Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Task__c.object
<CustomObject>
    <fields>
        <fullName>Scoping_Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scoping Feature</label>
        <referenceTo>Scoping_Feature__c</referenceTo>
        <relationshipLabel>Scoping Tasks</relationshipLabel>
        <relationshipName>Scoping_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoping Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

My Dev Org/src/classes/TestScopingTaskModel.cls
@isTest
private class TestScopingTaskModel {
	static testMethod void testGetRecord()
	{
		final String name = 'Test Name';
		final String details = 'Some details about this test scoping task.';
		
		Scope__c scope = new Scope__c();
		insert scope;
		
		Scoping_Feature__c feature = new Scoping_Feature__c();
		feature.Scope__c = scope.Id;
		insert feature;
		
		ScopingTaskModel model = new ScopingTaskModel();
		model.featureId = feature.Id;
		model.name = name;
		model.details = details;
				
		Test.startTest();
			Scoping_Task__c record = model.getRecord();
		Test.stopTest();
				
		System.assertNotEquals( null, record, 'The model should return a record.' );
		System.assertEquals( feature.Id, record.Scoping_Feature__c, 'The parent Feature should be populated.' );
	}
	
	static testMethod void testInsertRecord()
	{
		Scope__c scope = new Scope__c();
		insert scope;
		
		Scoping_Feature__c feature = new Scoping_Feature__c();
		feature.Scope__c = scope.Id;
		insert feature;
		
		ScopingTaskModel model = new ScopingTaskModel();
		model.featureId = feature.Id;
		//model.name = name;
		//model.details = details;
		model.estimate50 =1;
				
		Test.startTest();
			insert model.getRecord();
		Test.stopTest();
		
		System.assertNotEquals( null, model.getRecord(), 'maybe it would be, though?' );
	}
}