src/objects/Scoping_Feature__c.object
<CustomObject>
    <label>Scoping Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Task__c.object
<CustomObject>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Scoping_Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scoping Feature</label>
        <referenceTo>Scoping_Feature__c</referenceTo>
        <relationshipLabel>Scoping Tasks</relationshipLabel>
        <relationshipName>Scoping_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X50_Estimate__c</fullName>
        <label>50% Estimate</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X90_Estimate__c</fullName>
        <label>90% Estimate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Scoping Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

My Dev Org/src/classes/ScopingTaskModel.cls
public with sharing class ScopingTaskModel {
	public Id id { get; private set; }
	public Id featureId { get; set; }
	public String name { get; set; }
	public String details { get; set; }
	public Decimal estimate50 { get; set; }
	public Decimal estimate90 { get; set; }
	
	public Scoping_Task__c getRecord()
	{
		Scoping_Task__c record = new Scoping_Task__c( Id = id );
		
		record.Scoping_Feature__c = featureId;
		record.Name = name;
		record.Details__c = details;
		record.X50_Estimate__c = estimate50;
		record.X90_Estimate__c = estimate90;
		
		return record;
	}
	
	public void setRecord( Scoping_Task__c record )
	{
		id = record.Id;
		featureId = record.Scoping_Feature__c;
		name = record.Name;
		details = record.Details__c;
		estimate50 = record.X50_Estimate__c;
		estimate90 = record.X90_Estimate__c;
	}
}