src/objects/Scope__c.object
<CustomObject>
    <fields>
        <fullName>Code_Review__c</fullName>
        <label>Code Review</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Management__c</fullName>
        <label>Project Management</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reactive__c</fullName>
        <label>Reactive</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sum_of_X50_Estimates__c</fullName>
        <label>Sum of 50% Estimates</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Testing__c</fullName>
        <label>Testing</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Buffer__c +  Code_Review__c +  Deployment__c  +  Reactive__c  +  Project_Management__c +  Testing__c +  Sum_of_X50_Estimates__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scoping_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>Scope__c</referenceTo>
        <relationshipLabel>Scoping Features</relationshipLabel>
        <relationshipName>Scoping_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoping Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoping Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

My Dev Org/src/classes/ScopeModel.cls
global with sharing class ScopeModel {
	public Id id { get; private set; }
	public String name { get; set; }
	public Decimal codeReview { get; set; }
	public Decimal deployment { get; set; }
	public Decimal projectManagement { get; set; }
	public Decimal reactive { get; set; }
	public Decimal testing { get; set; }
	
	public Decimal total { get; private set; }
	public Decimal estimate50 { get; private set; }
	
	private ListModel featureList;
	
	public ScopeModel()
	{
		featureList = new ListModel();
	}
	
	public List<ScopingFeatureModel> features
	{
		get
		{
			List<ScopingFeatureModel> models = new List<ScopingFeatureModel>();
			for( ListModel.Element el : featureList.getList() )
			{
				models.add((ScopingFeatureModel)el);
			}
			return models;
		}
	}
	
	public void addFeature()
	{
		featureList.add(new ScopingFeatureModel());
	}
	
	public ScopingFeatureModel addFeature(Scoping_Feature__c featureRecord)
	{
		ScopingFeatureModel feature = new ScopingFeatureModel();
		
		feature.setRecord( featureRecord );
		
		featureList.add( feature );
		
		return feature;
	}
	
	public Scope__c getRecord()
	{
		Scope__c record = new Scope__c( Id = id );
		
		record.Name						= name;
		record.Code_Review__c			= codeReview;
		record.Deployment__c			= deployment;
		record.Project_Management__c	= projectManagement;
		record.Reactive__c				= reactive;
		record.Testing__c				= testing;
		
		return record;
	}
	
	public void setRecord( Scope__c record )
	{
		id					= record.Id;
		name				= record.Name;
		codeReview			= record.Code_Review__c;
		deployment			= record.Deployment__c;
		projectManagement	= record.Project_Management__c;
		reactive			= record.Reactive__c;
		testing				= record.Testing__c;
		
		total				= record.Total__c;
		estimate50			= record.Sum_of_X50_Estimates__c;
	}
}