src/objects/Serverside_State__c.object
<CustomObject>
    <description>This object will be used to store text representations of data on a per-user basis.

This object was first created for use with the Order Prioritization project.</description>
    <fields>
        <fullName>State_Chunk_10__c</fullName>
        <label>State Chunk 10</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_1__c</fullName>
        <label>State Chunk 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_2__c</fullName>
        <label>State Chunk 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_3__c</fullName>
        <label>State Chunk 3</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_4__c</fullName>
        <label>State Chunk 4</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_5__c</fullName>
        <label>State Chunk 5</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_6__c</fullName>
        <label>State Chunk 6</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_7__c</fullName>
        <label>State Chunk 7</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_8__c</fullName>
        <label>State Chunk 8</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Chunk_9__c</fullName>
        <label>State Chunk 9</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State_Token__c</fullName>
        <description>Piece of text to differentiate the Serverside States stored by functionality or application they correspond to.</description>
        <externalId>true</externalId>
        <label>State Token</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Serverside State</label>
    <nameField>
        <displayFormat>SST-{0000}</displayFormat>
        <label>Serverside State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Serverside States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServerSideStateUtil.cls
/** ServerSideStateUtil
*
* Utility allowing users to arbitrarily store data assosciated with a specific User and/or Session,
* potentially allowing developer to cut down on amount of data Salesforce needs to send during page
* refreshes or increase the amount of data that can be hadnled during single request by offloading
* some of said data to this utility as opposed to the built-in Visualforce viewstate
*
* 2011-12-06: Case# 00171892 / Michael Ng & William Saunders - Bluewolf - First pass at ServersideState utility
*
*/
public class ServerSideStateUtil {

	public static final String STATE_NOT_FOUND = 'Cannot find corresponding server side state!';
	public static final String STATE_NOT_STORED = 'Cannot properly store state!';
	public static final String STATE_TOO_LARGE = 'State is larger than record permits!';
	public static final String STATE_SLUG_MISSING = 'Must specify a text slug representing functionality this state belongs to.';

	public static final Integer TEXT_UPPER_LIMIT = 32768;
	public static final Integer STATE_CHUNK_COUNT = 10;
	public static final String STATE_CHUNK_PREFIX = 'State_Chunk_';
	public static final String STATE_TOKEN_DELIM = ' - ';

	public static void storeState( Id userId, String stateSlug, String theState ) {

		if ( theState.length() > STATE_CHUNK_COUNT * TEXT_UPPER_LIMIT )
			throw new ServerSideStateException( STATE_TOO_LARGE );

		List<String> stateSplits = splitByLength( theState, TEXT_UPPER_LIMIT );

		Serverside_State__c newState = new Serverside_State__c( State_Token__c = genStateToken( userId, stateSlug ) );

		for ( Integer splitIndex = 0; splitIndex < stateSplits.size(); splitIndex++ )
			newState.put( STATE_CHUNK_PREFIX + ( splitIndex + 1 ) + '__c', stateSplits[ splitIndex ] );		// +1 as field names dont start at 0

		try {

			upsert newState State_Token__c;

		} catch( System.Dmlexception dmlEx ) {

			throw new ServerSideStateException( STATE_NOT_STORED );

		}

	}

	public static String retrieveState( Id userId, String stateSlug ) {

		String concatenatedState = '';

		Serverside_State__c requestedState;

		try {

			requestedState = [ SELECT Id, state_chunk_1__c ,
									 state_chunk_2__c ,
									 state_chunk_3__c ,
									 state_chunk_4__c ,
									 state_chunk_5__c ,
									 state_chunk_6__c ,
									 state_chunk_7__c ,
									 state_chunk_8__c ,
									 state_chunk_9__c ,
									 state_chunk_10__c
									 FROM Serverside_State__c
									 WHERE State_Token__c = :genStateToken( userId, stateSlug ) ];

		} catch( System.Queryexception qEx ) {

			throw new ServerSideStateException( STATE_NOT_FOUND );

		}

		return concatState( requestedState );

	}

	private static String genStateToken( Id userId, String stateSlug ) {

		if ( stateSlug == null || stateSlug.trim() == '' )
			throw new ServerSideStateException( STATE_SLUG_MISSING );

		return userId + STATE_TOKEN_DELIM + stateSlug;

	}

	private static String concatState( Serverside_State__c stateToConcat ) {

		String concatString = '';

		for ( Integer stateFieldIndex = 1; stateFieldIndex < STATE_CHUNK_COUNT+1; stateFieldIndex++ )
			concatString += stateToConcat.get( STATE_CHUNK_PREFIX + stateFieldIndex + '__c' );

		return concatString;

	}

	//TODO: Move to StringUtils
	public static List<String> splitByLength( String stringToSplit, Integer length ) {

		List<String> splitStrings = new List<String>();
		Integer strPosit = 0;

		while ( strPosit < stringToSplit.length() ) {

			Integer endPosit = ( strPosit + length < stringToSplit.length() ) ? strPosit + length : stringToSplit.length();

			String strChunk = stringToSplit.substring( strPosit, endPosit );

			splitStrings.add( strChunk );

			strPosit = strPosit + length;

		}

		return splitStrings;

	}

	public class ServerSideStateException extends Exception { }

}