src/objects/SObjectField__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <label>SObject</label>
        <referenceTo>SObjectType__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>anytype</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>base64</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Combobox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DataCategoryGroupReference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DateTime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EncryptedString</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MultiPicklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SObjectField</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SObjectFields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SObjectType__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SObjectType</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SObjectTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchToBootstrapSObjectFieldInfo.cls
global class BatchToBootstrapSObjectFieldInfo implements Database.Batchable<SObject>, Database.Stateful
{
	public static final String BATCH_NAME = 'BootstrapSObjectFieldInfo';
	public static final String[] ERROR_EMAILS = new String[]{ 'acouch@bluewolf.com' };
	
	global String errors = '';
	global Map<String, Schema.SObjectType> globalDescribe;
	global Map<String, Map<String, Schema.SObjectField>> objectFieldsMap;
	
	global BatchToBootstrapSObjectFieldInfo()
	{
		globalDescribe = Schema.getGlobalDescribe();
	}
	
	global Database.QueryLocator start( Database.BatchableContext BC )
	{
		return Database.getQueryLocator( 'SELECT Id, Name, SObject__r.Name FROM SObjectField__c' );
	}
	
	global void execute( Database.BatchableContext BC, List<SObject> scope )
	{
		objectFieldsMap = new Map<String, Map<String, Schema.SObjectField>>();
		
		List<SObjectField__c> objectsToUpdate = new List<SObjectField__c>();
		
		for ( SObject someObject : scope )
		{
			SObjectField__c fieldToUpdate = (SObjectField__c)someObject;
			
			if( !objectFieldsMap.containsKey( fieldToUpdate.SObject__r.Name ) )
			{
				Schema.SObjectType token = globalDescribe.get( fieldToUpdate.SObject__r.Name );
				Schema.DescribeSObjectResult objectDescribe = token.getDescribe();
				
				Map<String, Schema.SObjectField> objectFields = objectDescribe.fields.getMap();
				
				objectFieldsMap.put( fieldToUpdate.SObject__r.Name, objectFields );
			}
			
			Schema.DescribeFieldResult fieldDescribe = objectFieldsMap.get( fieldToUpdate.SObject__r.Name ).get( fieldToUpdate.Name ).getDescribe();
			
			fieldToUpdate.Name = fieldDescribe.getName();
			fieldToUpdate.Label__c = fieldDescribe.getLabel();
			fieldToUpdate.Type__c = fieldDescribe.getType().name();
			
			objectsToUpdate.add( fieldToUpdate );
		}
		try
		{
			update objectsToUpdate;
		}
		catch( DMLException ex )
		{
			for( Integer i = 0; i < ex.getNumDml(); i++ )
			{
				errors += ex.getDmlMessage(i) + '\n';
			}
		}
	}
	
	global void finish( Database.BatchableContext BC ){
		
		AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
							JobItemsProcessed, TotalJobItems,
							CreatedBy.Email
							FROM AsyncApexJob
							WHERE Id =:bc.getJobId()];
		
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

		mail.setToAddresses( ERROR_EMAILS );
		mail.setSubject( 'Batch to ' + BATCH_NAME + ' ' + job.Status );
		
		String emailBody = 'Batch to ' + BATCH_NAME + ' processed '
						+ job.TotalJobItems
						+ ' batches with '
						+ job.NumberOfErrors
						+ ' failures.';
		if( errors != '' )
		{
			emailBody += '\n\n\nThe following errors occured:\n'+ errors;
		}
		
		mail.setPlainTextBody( emailBody );
		Messaging.sendEmail( new Messaging.SingleEmailMessage[]{ mail } );
	}
	
	private static testMethod void testBatch()
	{
		List<SObjectField__c> fields = [SELECT Id FROM SObjectField__c];
		delete fields;
		
		SObjectType__c accountObject = [SELECT Id FROM SObjectType__c WHERE Name = 'Account'];
		
		List<SObjectField__c> objectsToInsert = new List<SObjectField__c>();
		
		Schema.SObjectType token = Schema.getGlobalDescribe().get( 'Account' );
		
		if( null == token )
		{
			System.debug('ERROR on object Account');
		}
		else
		{
			Schema.DescribeSObjectResult objectDescribe = token.getDescribe();
			
			Map<String, Schema.SObjectField> objectFields = objectDescribe.fields.getMap();
			
			for( String fieldName : objectFields.keySet() )
			{
				SObjectField__c newField = new SObjectField__c();
				
				newField.Name = fieldName;
				newField.Label__c = fieldName;
				newField.SObject__c = accountObject.Id;
				
				objectsToInsert.add( newField );
			}
		}
		insert objectsToInsert;
		
		Test.startTest();
		
			Database.executeBatch( new BatchToBootstrapSObjectFieldInfo() );
		
		Test.stopTest();
		
		// @TODO: implement test
	}
}