src/objects/SObjectType__c.object
<CustomObject>
    <fields>
        <fullName>Key_Prefix__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Key Prefix</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SObjectType</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SObjectTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StandardSObjectRepository.cls
public class StandardSObjectRepository implements ISObjectRepository
{
	public SObject find( Id objectId )
	{
		String objectPrefix = ((String)objectId).substring(0,3);
		SObjectType__c objectType = [SELECT Name FROM SObjectType__c WHERE Key_Prefix__c = :objectPrefix];
		String query = 'SELECT Id, Name, LastModifiedDate FROM ' + objectType.Name + ' WHERE Id = :objectId';

		List<SObject> objectCandidates = Database.query( query );

		if( objectCandidates.isEmpty() )
			throw new SObjectNotFoundException();

		return objectCandidates[0];
	}

	public void save( SObject anSObject )
	{
		update anSObject;
	}

	public class SObjectNotFoundException extends Exception {}
}